services:
  tours-api:
    image: tours-api:latest
    build:
      context: .
      dockerfile: Services/Tours/Tours.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ToursDB=Server=tours_db;Initial Catalog=ToursDb;User Id=sa;Password=PlaninarskeTureToursDB*1;TrustServerCertificate=True;
    depends_on:
      - tours_db
        
#  identity-api:
#    image: identity-api:latest
#    build:
#      context: .
#      dockerfile: Services/Identity/Identity.API/Dockerfile
#    ports:
#      - "8081:8081"
#    environment:
#      - ASPNETCORE_URLS=http://+:8081
#      - ASPNETCORE_HTTP_PORTS=8081
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ConnectionStrings__IdentityDB=Server=identity_db;Initial Catalog=IdentityDb;User Id=sa;Password=IdentityDB*1;TrustServerCertificate=True;
#    depends_on:
#      - identity_db

  reviewing-api:
    image: reviewing-api:latest
    build:
      context: .
      dockerfile: Services/Review/Reviewing.API/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_URLS=http://+:8082
      - ASPNETCORE_HTTP_PORTS=8082
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ReviewingDB=Host=reviewing-db;Database=reviewing;Username=postgres;Password=postgres;SSL Mode=Disable
    depends_on:
      reviewing-db:
        condition: service_healthy
    restart: on-failure
  
  # yaml
  notifications-api:
    image: notifications-api:latest
    build:
      context: .
      dockerfile: Services/Notifications/src/WebApi/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_URLS=http://+:8083
      - ASPNETCORE_HTTP_PORTS=8083
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://root:notificationspwd@notifications-mongo:27017/?authSource=admin
      - MongoDb__Database=notifications
    depends_on:
       notifications-mongo:
         condition: service_healthy
    restart: on-failure


  notifications-mongo:
    image: mongo:7
    container_name: notifications-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "notificationspwd"
      MONGO_INITDB_DATABASE: notifications
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5



  tours_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tours_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PlaninarskeTureToursDB*1"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"

#  identity_db:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    container_name: identity_db
#    environment:
#      ACCEPT_EULA: "Y"
#      MSSQL_SA_PASSWORD: "IdentityDB*1"
#      MSSQL_PID: "Developer"
#    ports:
#      - "1435:1433"

  reviewing-db:
    image: postgres:16
    container_name: reviewing-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviewing
    ports:
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3