services:
  tours-api:
    image: tours-api:latest
    build:
      context: .
      dockerfile: Services/Tours/Tours.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ToursDB=Server=tours_db;Initial Catalog=ToursDb;User Id=sa;Password=PlaninarskeTureToursDB*1;TrustServerCertificate=True;
    depends_on:
      - db
  identity-api:
    image: identity-api:latest
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IdentityDB=Server=identity_db;Initial Catalog=IdentityDb;User Id=sa;Password=IdentityDB*1;TrustServerCertificate=True;
    depends_on:
      - db


  tours_db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "PlaninarskeTureToursDB*1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  identity_db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "IdentityDB*1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"