services:
  tours-api:
    image: tours-api:latest
    build:
      context: .
      dockerfile: Services/Tours/Tours.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ToursDB=Server=db;Initial Catalog=ToursDb;User Id=sa;Password=PlaninarskeTureToursDB*1;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "PlaninarskeTureToursDB*1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"