// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tours.Infrastructure;

#nullable disable

namespace Tours.Infrastructure.Migrations
{
    [DbContext(typeof(ToursDbContext))]
    [Migration("20251014221812_AddTourEnrollments")]
    partial class AddTourEnrollments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tours.Domain.Entities.Mountain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mountains");
                });

            modelBuilder.Entity("Tours.Domain.Entities.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MountainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Weather")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MountainId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Tours.Domain.Entities.TourEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TourId", "UserId")
                        .IsUnique();

                    b.ToTable("TourEnrollments");
                });

            modelBuilder.Entity("Tours.Domain.Entities.Tour", b =>
                {
                    b.HasOne("Tours.Domain.Entities.Mountain", "Mountain")
                        .WithMany("Tours")
                        .HasForeignKey("MountainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Tours.Domain.ValueObjects.HikerRange", "HikerRange", b1 =>
                        {
                            b1.Property<Guid>("TourId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MaxNumberOfPeople")
                                .HasColumnType("int")
                                .HasColumnName("NaxNumberOfPeople");

                            b1.Property<int>("MinNumberOfPeople")
                                .HasColumnType("int")
                                .HasColumnName("MinNumberOfPeople");

                            b1.Property<int>("NumberOfRegisteredPeople")
                                .HasColumnType("int")
                                .HasColumnName("NumberOfRegisteredPeople");

                            b1.HasKey("TourId");

                            b1.ToTable("Tours");

                            b1.WithOwner()
                                .HasForeignKey("TourId");
                        });

                    b.Navigation("HikerRange");

                    b.Navigation("Mountain");
                });

            modelBuilder.Entity("Tours.Domain.Entities.TourEnrollment", b =>
                {
                    b.HasOne("Tours.Domain.Entities.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Tours.Domain.Entities.Mountain", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
